# Generated by Django 5.2.6 on 2026-02-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_current_theme_alter_userprofile_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='sidebar_color',
            field=models.CharField(default='#1f2937', max_length=7),
        ),
    ]
