# Generated by Django 5.2.6 on 2026-02-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_activity_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('theme_created', 'Theme Created'), ('theme_changed', 'Theme Changed'), ('profile_updated', 'Profile Updated'), ('profile_created', 'Profile Created'), ('avatar_updated', 'Avatar Updated'), ('photo_uploaded', 'Photo Uploaded'), ('photo_updated', 'Photo Updated'), ('photo_deleted', 'Photo Deleted'), ('task_created', 'Task Created'), ('task_deleted', 'Task Deleted'), ('note_created', 'Note Created'), ('note_deleted', 'Note Deleted')], max_length=50),
        ),
    ]
